name: Renovate Dependency Updates

on:
  schedule:
    - cron: "0 7 * * 1" # Monday 10:00 UTC+3
  workflow_dispatch:

concurrency:
  group: renovate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: https://hangar.nixthedev.ru/actions/checkout@v4

      - name: Run Renovate
        uses: docker://docker.io/renovate/renovate:full
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_PLATFORM: "forgejo"
          RENOVATE_ENDPOINT: "https://hangar.nixthedev.ru/api/v1/"
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          #GITHUB_COM_TOKEN: ${{ secrets.GH_COM_TOKEN }}
          LOG_LEVEL: "debug"
